mongo:
  image: mongo

app:
  build: .
  volumes:
    - .:/app
  links:
    - mongo:mongo
  ports:
    - 8080:8080
  environment:
    - MONGODB_HOST=mongo
  working_dir: /app
  command: fab run_server
